// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: refreshToken.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUserFromRefreshToken = `-- name: GetUserFromRefreshToken :one
SELECT token, created_at, updated_at, user_id, expires_at, revoked_at FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) GetUserFromRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getUserFromRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const newRefreshToken = `-- name: NewRefreshToken :one
INSERT INTO refresh_tokens(token, created_at, updated_at, user_id, expires_at, revoked_at)Values(
    $1,
    NOW(),
    NOW(),
    $2,
    $3,
    null
)
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type NewRefreshTokenParams struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) NewRefreshToken(ctx context.Context, arg NewRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, newRefreshToken, arg.Token, arg.UserID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeTokenFromRefreshToken = `-- name: RevokeTokenFromRefreshToken :exec
UPDATE refresh_tokens 
    SET revoked_at = NOW(),
    updated_at = NOW()
    WHERE token = $1
`

func (q *Queries) RevokeTokenFromRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeTokenFromRefreshToken, token)
	return err
}
